"""add email to user, due_date and reminder flags to task

Revision ID: 22693d7de121
Revises: a0dcb11932b6
Create Date: 2026-09-12 23:23:10.870697

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22693d7de121'
down_revision: Union[str, Sequence[str], None] = 'a0dcb11932b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('reminder_sent', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('overdue_notified', sa.Boolean(), nullable=False))
    with op.batch_alter_table('task') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    with op.batch_alter_table('task') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('task', 'overdue_notified')
    op.drop_column('task', 'reminder_sent')
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
