"""add oauth_provider and make hashed_password nullable

Revision ID: d7b8f98f6232
Revises: 7ae542fdacf7
Create Date: 2026-09-27 12:56:47.420440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b8f98f6232'
down_revision: Union[str, Sequence[str], None] = '7ae542fdacf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_provider',  sa.String() , nullable=True))
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'oauth_provider')
    # ### end Alembic commands ###
